### ISSUE TITLE
Compatibility with Midi-QOL

### ISSUE THREAD

**Issue by easy772** [taragnor/foundry-security#1]
Hi,

I am unable to get this working with the Midi-QOL module on foundry. Are there any plans to extend functionality to modules that alter the default chat message?

**Comment by taragnor** [comment]
Unfortunately Midi-QOL doesn't use asynchronous die rolling so it won't be compatible until that module updates. So until they update to async, it won't be compatible. Foundry itself wants to move towards all rolls being async eventually, so hopefully the developers of Midi-QOL will change over. But right now nothing I can do on my end.
